[package]
name = "xacml-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = {version = "0.37.2", features = ["serialize"]}
# serde-xml-rs = "0.6.0"
serde = { version = "1.0.215", features = ["derive"]}
